spring.application.name=projetPadel1
jwt.secret=aVeryLongAndComplexSecretKeyThatIsAtLeast256BitsLongForHS256AlgorithmAndShouldBeKeptConfidential
jwt.expiration=86400000

# PostgreSQL (docker-compose: localhost:5440)
spring.datasource.url=jdbc:postgresql://localhost:5440/padelService
spring.datasource.username=padel
spring.datasource.password=padel
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate schema management
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

